### ISSUE TITLE
[疑问]开启 HTTPS 访问情况下，无法连接到 Aria2 后端

### ISSUE THREAD

**Issue by fejich** [wahyd4/aria2-ariang-docker#10]
- 系统环境： Ubuntu 18.04.1 LTS

- 安装了最新的社区版的 Docker CE

启动命令：
` docker run -d --name ariang -p 80:80 -p 6800:6800 -p 443:443 -e ENABLE_AUTH=true -e RPC_SECRET=Hello -e DOMAIN=我的域名 -e ARIA2_USER=user -e ARIA2_PWD=pwd -v /home/fejich:/data wahyd4/aria2-ui`

症状为：
访问我的域名自动以 HTTPS 方式打开了 AriaNg 前端
但是无法连接到 Aria2 后端

后续测试了不启用 HTTPS ，能正常工作。

要正常使用 HTTPS 需要手动指定 SSL 证书吗？
（ -v /yoursslkeys/:/root/conf/key ）

能否做到自动化启用 Let's Encrypt 生成的证书？

**Comment by wahyd4** [comment]
Aria2要启用SSL需要手动指定证书的，证书自动匹配暂时还没实现。

**Comment by fejich** [comment]
回复好快，谢谢解答。
