### ISSUE TITLE
Why does AriaNG show that I am connected without entering a the RPC_SECRET

### ISSUE THREAD

**Issue by phoenixsfly** [wahyd4/aria2-ariang-docker#100]
I have set the env variable RPC_SECRET, however when I open AriaNG, it shows that  I am connected  even if the rpc-secret in the ariang is blank.

Is this because the program is filling in the password internally or because I need to set rpc secert on aria2.conf ?

**Comment by wahyd4** [comment]
Glad you noticed that it's because we have prefilled for you when the program starts to run
https://github.com/wahyd4/aria2-ariang-docker/blob/d7599bda00efa4a5e856b07af11eb793801d5332/aria2c.sh#L5

For more details, please go check https://github.com/wahyd4/aria2-ariang-docker/pull/85
