### ISSUE TITLE
add rclone and heroku support

### ISSUE THREAD

**Issue by telegrambotdev** [wahyd4/aria2-ariang-docker#101]
Kindly add rclone support for uploading to gdrive also add heroku deploy button

**Comment by wahyd4** [comment]
@telegrambotdev Why not using a `rclone` docker image to achieve the storage backup feature?

For the Heroku part, regarding this docker images uses P2P downloading files, I wouldn't recommend you to run it in a public cloud platform. But you can always do it by yourself.

**Comment by AmirulAndalib** [comment]
pls Write steps On how to do It Heroku aint working With Node.Js buildpack and Cant detect Language of this Repp 🙄
