### ISSUE TITLE
dorker run with DOMAIN get error on caddy

### ISSUE THREAD

**Issue by Abeperspiration** [wahyd4/aria2-ariang-docker#102]
**Describe the bug**
running with DOMAIN option gets an error on docker
logs showed with 

```
**** update uid and gid to 1000:1000 ****
usermod: no changes
**** give caddy permissions to use low ports ****
forego        | starting filebrowser.1 on port 5000
forego        | starting caddy.1 on port 5100
forego        | starting aria2c.1 on port 5300
caddy.1       | Run aria2c and ariaNG
caddy.1       | Using caddy without Basic Auth
caddy.1       | 2020/06/05 20:23:51 decoding certificate metadata: unexpected end of JSON input
forego        | sending SIGTERM to filebrowser.1
forego        | sending SIGTERM to aria2c.1
```

then the container shut down

**To Reproduce**
Steps to reproduce the behaviour:
1. run 
```
docker run -d --name aria2-ui -p 80:80 -p 444:443 -e DOMAIN=https://****.*****.**** wahyd4/aria2-ui
```
or
```
docker run -d --name aria2-ui -p 80:80 -p 443:443 -e DOMAIN=https://****.*****.**** wahyd4/aria2-ui
```
**Expected behaviour**
container runs normally

**Comment by Abeperspiration** [comment]
It seems something wrong with 'Caddyfile'?
'Make sure to chown your $DOMAIN so that the Caddy binary can access it'
[https://caddy.community/t/solved-fails-to-start-decoding-certificate-metadata-unexpected-end-of-json-input/5192](url)

**Comment by wahyd4** [comment]
Have you updated the DNS record to bind your IP to that domain?

**Comment by TheLonelinessOfHS** [comment]
Same issue here. I am sure that I have correctly setup my DNS record.

**Comment by wahyd4** [comment]
@TheLonelinessOfHS Thanks for reporting this issue, I will have a double-check later.

**Comment by wahyd4** [comment]
Hi @Abeperspiration @TheLonelinessOfHS , please manually pull the latest docker image which solved this issue, then recreate a docker again.
```
docker pull wahyd4/aria2-ui:latest
```
