### ISSUE TITLE
data目录映射到usb移动硬盘以后，下载一开始没有速度。

### ISSUE THREAD

**Issue by gexiaopeng** [wahyd4/aria2-ariang-docker#105]
我把data下载目录映射到usb移动硬盘以后，通过115创建下载任务，开始下载的速度是0，一般要过一段时间才正式开始下载（文件大小不同等待的时间也不同）。后来发现usb的文件大小会慢慢变大，等达到目标大小以后就开始下载。但如果我把data映射到硬盘，下载的任务会马上开始的（硬盘的文件大小一开始就是目标大小）.请问这个是什么原因？

**Comment by gexiaopeng** [comment]
补充一下：aria2安装在群晖服务上。

**Comment by hametan** [comment]
> 补充一下：aria2安装在群晖服务上。

你的是群晖的docker里吗？我的一直提示权限不足，

**Comment by wahyd4** [comment]
@hametan is this error from docker logs? And what are the parameters you used to run this container?

**Comment by gexiaopeng** [comment]
> docker

是安装在docker里的，权限不足可以把下载的文件夹权限设置一下，同时增加everyone

**Comment by gexiaopeng** [comment]
> @hametan is this error from docker logs? And what are the parameters you used to run this container?

docker没有错误日志，这个现象不是错误，只是开始下载的前面几分钟速度为0，然后能正常下载。(配置上在aria2的下载路径修改为/data/movies，docker也配置了/data/movies的映射 ，movies目录是移动硬盘),另外发现群晖下载目录的文件大小在慢慢变大，等达到目标大小以后才开始下载。具体看附件图片。
![QQ截图20200724085244](https://user-images.githubusercontent.com/7857056/88352305-e6875b00-cd8b-11ea-921b-57a0a5fefe18.png)
![QQ截图20200724085502](https://user-images.githubusercontent.com/7857056/88352312-e8e9b500-cd8b-11ea-86f9-90d337f5883a.png)
![QQ截图20200724085621](https://user-images.githubusercontent.com/7857056/88352314-e9824b80-cd8b-11ea-8475-c386efeae340.png)
![QQ截图20200724085722](https://user-images.githubusercontent.com/7857056/88352317-e9824b80-cd8b-11ea-8e83-73111c9a34fb.png)
![QQ截图20200724085740](https://user-images.githubusercontent.com/7857056/88352318-eab37880-cd8b-11ea-889c-aebda1746508.png)

**Comment by gexiaopeng** [comment]
补充：如果把aria2的下载目录设置为/data （物理目录是内置硬盘），就会立即下载，并且下载目录下面的文件大小是目标大小。

**Comment by gexiaopeng** [comment]
再补充：/data/moives的物理位置是插在usb的移动硬盘。

**Comment by wahyd4** [comment]
Got it, this might because Aria2 was trying to create a file block has that
size, let's say 2 GB, it can take a while.

But I am not 100% sure, I encourage you to mount an NFS folder to your host
as the downloading folder if you want to external storage, instead of a USB
drive.

Kind regards,
Junwei Zhao

**Comment by wahyd4** [comment]
Thanks for your update @gexiaopeng . Unfortunately, I don't think I can do too much within this project to assist you to solve this issue. I will close this issue now, if you have anything other question related to this project, please feel free to raise a new issue. Please consider using English first.
