### ISSUE TITLE
cause: Permission denied

### ISSUE THREAD

**Issue by hametan** [wahyd4/aria2-ariang-docker#106]
在群晖中的docker创建之后，下载文件时提示cause: Permission denied

**Comment by wahyd4** [comment]
Please provide some more details, what's the configuration you have to run this docker image, and what's the docker logs looks like?

**Comment by gexiaopeng** [comment]
> 在群晖中的docker创建之后，下载文件时提示cause: Permission denied

在配置的下载目录属性里修改权限，增加everyone
![QQ截图20200724092548](https://user-images.githubusercontent.com/7857056/88353389-dcfff200-cd8f-11ea-81ed-e287647e22c0.png)
