### ISSUE TITLE
Rclone doesn't work with Google Drive when HTTPS is enabled in caddy

### ISSUE THREAD

**Issue by acc557** [wahyd4/aria2-ariang-docker#125]
**Describe the bug**
Rclone doesn't work with google drive when HTTPS is enabled in caddy

**To Reproduce**
1. Go to https://example.com/rclone
2. create a config
3. use  Google Drive 
4. The screen jumps back to `https://example.com/rclone/#/dashboard` instead of google login page.

**Expected behavior**
login to google account.

Try upgrade Rclone or change the configuration?

**Comment by wahyd4** [comment]
Hi @acc557 Does this only happen when HTTPS is enabled Or you just tested HTTPS?

You can follow the guide I have tested against Google drive before to give a try. https://github.com/wahyd4/aria2-ariang-docker/issues/118

**Comment by acc557** [comment]
I have just tested HTTPS. I followed your guide and now it works. Thanks!
