### ISSUE TITLE
群晖安装了web端无法打开

### ISSUE THREAD

**Issue by Lasx** [wahyd4/aria2-ariang-docker#131]
默认80 443 无法使用，修改了端口浏览器打开页面空白

**Comment by wahyd4** [comment]
Please paste the full command you used to run the container.

**Comment by wahyd4** [comment]
Hi @Lasx, I will close it now due to no further feedback has been provided. 
But feel free to create a new one with more details.

**Comment by wahyd4** [comment]
Hi @Lasx if the issue you experienced was caused by failed to download Rclone UI from Github, please try to pull the latest version docker image and set environment variable `ENABLE_RCLONE` to `false` to disable Rclone, then your container should work.
