### ISSUE TITLE
自定义ssl证书时Cloudflare提示不能连接服务器

### ISSUE THREAD

**Issue by xratzh** [wahyd4/aria2-ariang-docker#132]
- 情况1：

默认是let's encrypt签订的证书：
_docker run -d --name aria2-ui -p 80:80 -p 443:443 -v /data/data:/data -v /data/config/filebrowser.db:/app/filebrowser.db -v /data/config/key:/app/conf/key -e DOMAIN=https://aaa.bbb.com wahyd4/aria2-ui_
https打开都正常，切换对应的crt、key内容为Cloudflare自签证书，然后再restart，系统正常切换到Cloudflare证书了。

- 情况2：

/data/config/key下先创建对应aria2名称的Cloudflare自签证书，命令一致，再重新创建容器，服务运行正常，但是网页打开Cloudflare提示525，Cloudflare无法连接服务器。

- 情况3：

_docker run -d --name aria2-ui -p 80:80 -p 443:443 -v /data/data:/data -v /data/config/filebrowser.db:/app/filebrowser.db -v /data/config/key/aria2.crt:/app/conf/key/aria2.crt -v /data/config/key/aria2.key:/app/conf/key/aria2.key -e DOMAIN=https://aaa.bbb.com wahyd4/aria2-ui_
如情况二网页报错521，提示服务器没有开启。

请问如何使用自定义的SSL证书？需要docker exec后到哪里进行修改再docker restart？
谢谢

**Comment by wahyd4** [comment]
Unfortunately, I have to close it due to having no further updates in the last more than 2 years.
