### ISSUE TITLE
Improve the doc about the environment DOMAIN

### ISSUE THREAD

**Issue by youngyangH** [wahyd4/aria2-ariang-docker#141]
Please help to add the information about the environment `DOMAIN` as follow:
Please use your **IP address**(Public or private IP address) as the `DOMAIN` environment if you don't have a domain. For example:
You need to use the `10.10.10.2` as the `DOMAIN` environment if you want to access the aria2 with the IP `10.10.10.2` in the browser. The command can be `docker run -d --name Aria2 -p 80:80 -p 6800:6800 -e DOMAIN=http://10.10.10.2 -v /data:/data wahyd4/aria2-ui`.

You will get a blank page if your environment `Domain` isn't right.

**Comment by wahyd4** [comment]
Hi @youngyangH, thanks for your suggestion. I will consider it.
But in terms of your case, if you don't have public IP or you don't want to enable auto HTTPS, just leave the `DOMAIN` as it is, which means to set/change that environment variable. It should work.

**Comment by youngyangH** [comment]
I think many people would like to deploy the aria2 in one device(device1) which is for downloading and use aria2 in another device(device2) to trigger the download. The default DOMAIN is `http://localhost`. It will be a blank page if I use the IP of the device1 directly. I fix the issue by changing the environment `DOMAIN` to the IP of the device1. BTW, I test in the Raspberry Pi.
-------------------
Just want to save time for someones. :)

**Comment by wahyd4** [comment]
Okay, let's make it clear. If you access the app from device 1, then you
can use local host as well as it's 10.x IP to access it. But if you are
access from your laptop, then you must use device1's non localhost IP to
access it, because in this case localhost means your laptop not device1.

**Comment by Junyih** [comment]
> I think many people would like to deploy the aria2 in one device(device1) which is for downloading and use aria2 in another device(device2) to trigger the download. The default DOMAIN is `http://localhost`. It will be a blank page if I use the IP of the device1 directly. I fix the issue by changing the environment `DOMAIN` to the IP of the device1. BTW, I test in the Raspberry Pi.
> 
> Just want to save time for someones. :)


I think you got the point why i kept getting blank pages when deploying the container on another machine.
https://github.com/wahyd4/aria2-ariang-docker/issues/133

Adding the env DOMAIN fixed the problem, thank you.

**Comment by wahyd4** [comment]
Hi @Junyih @youngyangH , thanks for your reporting. I didn't release the remote access error was an issue until #142 .

I made a fix just now, please pull the latest version of the image and give a try by not overriding `DOMAIN` environment variable. Please let me know how it goes.

**Comment by Junyih** [comment]
> Hi @Junyih @youngyangH , thanks for your reporting. I didn't release the remote access error was an issue until #142 .
> 
> I made a fix just now, please pull the latest version of the image and give a try by not overriding `DOMAIN` environment variable. Please let me know how it goes.

Now works for me without DOMAIN env :)
