### ISSUE TITLE
N1 docker bug 

### ISSUE THREAD

**Issue by fanyh123** [wahyd4/aria2-ariang-docker#142]
first thanks for your openSource、your work
***
N1(斐讯) use command `docker run -d --name ariang   -p 80:80  -e PUID=0   -e PGID=0 -e ENABLE_RCLONE=false  wahyd4/aria2-ui`
then , i open my n1 ip http://192.168.2.221,192.168.2.221/ui  , all website is blank, i check log ,not find any error
the log is:
`forego        | starting filebrowser.1 on port 5000,
forego        | starting caddy.1 on port 5100,
forego        | starting aria2c.1 on port 5300,
forego        | starting rclone.1 on port 5600,
rclone.1      | Skip starting Rclone as it's been disabled,
caddy.1       | Run aria2c and ariaNG,
caddy.1       | Using caddy without Basic Auth,
aria2c.1      | Start aria2 with standard mode,
caddy.1       | {"level":"info","ts":1611071486.8261452,"msg":"using provided configuration","config_file":"/usr/local/caddy/Caddyfile","config_adapter":"caddyfile"},
aria2c.1      | ,
aria2c.1      | 01/19 15:51:26 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.,
aria2c.1      | ,
aria2c.1      | 01/19 15:51:26 [NOTICE] IPv4 RPC: listening on TCP port 6800,
caddy.1       | {"level":"info","ts":1611071486.8450887,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["[::1]:2019","127.0.0.1:2019","localhost:2019"]},
filebrowser.1 | 2021/01/19 15:51:26 No config file used,
caddy.1       | {"level":"info","ts":1611071486.8480499,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x40002ae000"},
caddy.1       | {"level":"info","ts":1611071486.8480937,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80},
caddy.1       | {"level":"info","ts":1611071486.8523579,"logger":"tls","msg":"cleaned up storage units"},
caddy.1       | {"level":"info","ts":1611071486.8537314,"msg":"autosaved config","file":"/app/.caddy/config/caddy/autosave.json"},
caddy.1       | {"level":"info","ts":1611071486.8537984,"msg":"serving initial configuration"},
filebrowser.1 | 2021/01/19 15:51:27 Listening on 127.0.0.1:8080,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | ,
aria2c.1      | 01/19 15:51:37 [NOTICE] Serialized session to '/app/conf/aria2.session' successfully.,
caddy.1       | {"level":"info","ts":1611071546.8939655,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"127.0.0.1:34900","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/","headers":{"User-Agent":["curl/7.69.1"],"Accept":["*/*"]}},"common_log":"127.0.0.1 - - [19/Jan/2021:15:52:26 +0000] \"GET / HTTP/1.1\" 200 4245","duration":0.00557804,"size":4245,"status":200,"resp_headers":{"Server":["Caddy"],"Content-Type":["text/html; charset=utf-8"],"X-Xss-Protection":["1; mode=block"],"Date":["Tue, 19 Jan 2021 15:52:26 GMT"]}},
caddy.1       | {"level":"info","ts":1611071577.8288693,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.2.196:61525","proto":"HTTP/1.1","method":"GET","host":"192.168.2.221","uri":"/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-CN,zh;q=0.9,en;q=0.8"],"Cookie":["_ga=GA1.1.1623177598.1594616898; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _gid=GA1.1.1337759052.1611066616; connect.sid=s%3AiNYyMr1FijAaSVzLWVSBai8TyOC0_hr0.EyIEbZxobs4W4fAO7PYOEpv1AsSwRjVNtoxIEZCdN88"],"Connection":["keep-alive"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"]}},"common_log":"192.168.2.196 - - [19/Jan/2021:15:52:57 +0000] \"GET / HTTP/1.1\" 0 0","duration":0.000011625,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}},
caddy.1       | {"level":"info","ts":1611071578.5924575,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.2.196:61525","proto":"HTTP/1.1","method":"GET","host":"192.168.2.221","uri":"/favicon.ico","headers":{"Accept":["image/avif,image/webp,image/apng,image/*,*/*;q=0.8"],"Referer":["http://192.168.2.221/"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-CN,zh;q=0.9,en;q=0.8"],"Cookie":["_ga=GA1.1.1623177598.1594616898; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _gid=GA1.1.1337759052.1611066616; connect.sid=s%3AiNYyMr1FijAaSVzLWVSBai8TyOC0_hr0.EyIEbZxobs4W4fAO7PYOEpv1AsSwRjVNtoxIEZCdN88"],"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"]}},"common_log":"192.168.2.196 - - [19/Jan/2021:15:52:58 +0000] \"GET /favicon.ico HTTP/1.1\" 0 0","duration":0.000012459,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}},`

***
 when i use command `docker run -d --name ariang   -p 80:80 -p 6800:6800  -e PUID=0   -e PGID=0 -e ENABLE_RCLONE=false  wahyd4/aria2-ui`
then i use chrome extensions "AriaNG" connect 192.168.2.221:6900/jsonrpc , aria2 status is success
![image](https://user-images.githubusercontent.com/15026816/105058008-c02f4780-5ab0-11eb-8380-91040d3bed5a.png)
and the healthy mean is what? 
![image](https://user-images.githubusercontent.com/15026816/105058244-f7055d80-5ab0-11eb-9836-27566b9775e6.png)

**Comment by wahyd4** [comment]
Hi @fanyh123, thanks for your reporting, I didn't this was an issue.
The remote access issue was because the default domain I used was `DOMAIN=http://localhost` which only allows local access in Caddy v2. In v1, the same config was fine.

But now I have fixed this issue via https://github.com/wahyd4/aria2-ariang-docker/pull/143, please give a try and let me know how it goes.

**Comment by wahyd4** [comment]
I will close this issue now given there is no further update
