### ISSUE TITLE
Possible to change aria2ng to use root directory URL?  (ie. change base url)

### ISSUE THREAD

**Issue by sofakng** [wahyd4/aria2-ariang-docker#148]
Thanks for the fantastic docker container!

Is it possible to switch aria2ng to use the default url (http://0.0.0.0) instead of requiring the subdirectory?  (http://0.0.0.0/ui)

I'd much rather require a subdirectory use the filebrowser (or disable it entirely).

Thanks!

**Comment by wahyd4** [comment]
Hi @sofakng thanks for your feedback, I can see AriaNG make most sense to you. But this doesn't sound like super convincing for everyone.

**Comment by FrancYescO** [comment]
+1

**Comment by wahyd4** [comment]
Hi everyone, I have made a pull request to address your feedback. In the newer version, the root path will be AriaNg and `/files` will be Filebrowser.

**Comment by wahyd4** [comment]
I just released merged this change to master and published it with the tag `wahyd4/aria2-ui:edge`. 

Can you guys help test this docker image tag, so that we can release it with the `latest` tag as soon as possible?

**Comment by earthruby** [comment]
i have tried the edge version and it works like a charm. thanks for your update.

BTW, i have another question, my docker image never works if i mount /app/filebrowser.db, not for the latest version nor edge version

not sure if anyone is facing the same problem as i do...

i run this docker image under Synology NAS Docker, it keeps restarting and shows Docker container: Aria2-UI stopped unexpectedly. (No detail error message under Docker log)

however, if i remove /app/filebrowser.db from volume, this image works normally.

any idea on how to solve this?

thanks!

![image](https://user-images.githubusercontent.com/62000365/113951905-21acba00-9847-11eb-9f59-856df1996187.png)

**Comment by wahyd4** [comment]
Hi @earthruby can you raise this filebrowser.db volume thing as a new issue?  So that we can talk about it separately.

By the way, I am currently mounting this `fielbrowser.db` and it works fine, I will try to reproduce the issue you faced.

Anyway, let's talk about this in another issue.

**Comment by wahyd4** [comment]
For this issue, the `latest` has all the features as `edge` and is ready for use now. 
I will close it now.
