### ISSUE TITLE
Rclone not working after adding rclone.conf in conf folder

### ISSUE THREAD

**Issue by vpn12** [wahyd4/aria2-ariang-docker#149]
Hi,

Is there any change in format of the rclone.conf added in conf folder ? or should it be one liner by using \n for new lines ?

[xxxxxmydrive]
type = drive
scope = drive
token = {"access_token":"xxxxxxxxWpEAYma6j6t3p4","expiry":"2021-02-09T15:39:18.48858272Z"}

Pls advice

Thanks!

**Comment by wahyd4** [comment]
Can you provide more detailed error logs?

Kind regards,
Junwei Zhao

**Comment by vpn12** [comment]
Sir,
Actually, there is no error logs. Everything is working fine except rclone. I have added rclone.conf in conf folder as per the instructions written in readme.md, but rclone is not working. **Pls explain me how to use rclone.**
Also, tell if the rclone.conf format is correct or not, or there is any other specific format.

Pls advice
Thanks

**Comment by wahyd4** [comment]
Please follow the guide from the comments to setup Google drive.
https://github.com/wahyd4/aria2-ariang-docker/issues/118

**Comment by vpn12** [comment]
Is there any way other than command line ? As there is no option to use command line in my PaaS/vps. I am using dockerfile to deploy. Previously, I have deployed AriaNg from dockerfile of https://github.com/maple3142/aria2c-ariang which is totally working fine. In this I have pasted rclone.conf as env variable and rclone is working fine. You can checked that !
But, I want to deploy this. Pls tell if there is any way other than command-line. Pls advice.

**Comment by wahyd4** [comment]
HI @vpn12 you can follow the guide I mentioned to get authenticated with Google drive by running this docker image locally. 
Then you can make a copy of the `rclone.conf` file,  next you can mount your config files to `/app/conf` folder. more details can be found here https://github.com/wahyd4/aria2-ariang-docker#supported-volumes

**Comment by wahyd4** [comment]
Closed due to no further updates
