### ISSUE TITLE
File manager is in loading status infinitely

### ISSUE THREAD

**Issue by GreenHatHG** [wahyd4/aria2-ariang-docker#15]
我用服务器ip登陆后，浏览器显示的ip是ip/files/files，此时显示正在加载中，只有我手动把网址改成ip/files才能刷新出来
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1fyzicg5zvrj31010cm74i.jpg">
重现概率大概是100%

**Comment by wahyd4** [comment]
Have you run something from repo [aria2-ariang-x-docker-compose](https://github.com/wahyd4/aria2-ariang-x-docker-compose)?  
If you have then this is because of the browser cache. You can try open the address in incognito mode or clean the cache or use another browser.

**Comment by GreenHatHG** [comment]
我是以这个启动方式`docker run -d --name aria2-ui -p 80:80 -p 6800:6800 wahyd4/aria2-ui`运行的，对了，我在docker里面加了个baidupcs-web服务，不知道是不是冲突了，忘了提了，不好意思，
[liuzhuoling2011/baidupcs-web](https://github.com/liuzhuoling2011/baidupcs-web)

**Comment by wahyd4** [comment]
It's not a good idea to run another application in this docker image, but I don't think it will cause this issue.
Have you tested the URL in other browsers? Please give a go. 
By the way, I couldn't reproduce the issue you mentioned.

**Comment by GreenHatHG** [comment]
我在微软的edge里面测试的话就一直加载中，chrome的话重新进入那个网址就能显示了。可能就是那个的问题，我等会重新弄下，感谢你的回答

**Comment by ljycrystal** [comment]
目前的镜像file manager会卡在加载中的问题，目前我自己测试，在IE11，猎豹，Edge都有问题，Chrome和手机自带浏览器（MIUI 9）可以正常显示。原作者更新了，该问题在https://github.com/filebrowser/filebrowser/issues/587。

**Comment by wahyd4** [comment]
@ljycrystal  Thanks for your update, actually the latest version of `filemanger` has a very serious issue which caused the entire application can't be loaded. I do acknowledge the issue you mention exists. I will keep an eye on this.

By the way, the Chrome browser on iOS works fine.

**Comment by wahyd4** [comment]
@GreenHatHG  Could you please leave this issue open?  So we can track and fix it when the `filemanager` fixed its own issue.

**Comment by GreenHatHG** [comment]
当然了，抱歉

**Comment by wahyd4** [comment]
@GreenHatHG  By the way, I just created a discussion about whether to add some other downloading tools(e.g. `cloud-torrent`) to the docker compose repo. If you can express your attitude that would be awesome, thank you. https://github.com/wahyd4/aria2-ariang-x-docker-compose/issues/59

**Comment by fanyh123** [comment]
![image](https://user-images.githubusercontent.com/15026816/53097797-435e6080-355d-11e9-927b-dee5a6d8d52c.png)
http://myip/files 打不开。发现所需资源文件是404

**Comment by wahyd4** [comment]
@fanyh123 I guess your case has been solved in #17

**Comment by wahyd4** [comment]
Since the file-brower maintainer didn't fix this issue for a quite long time, I have decided to fix this issue by moving the `file-browser` to root path.  So the current URLs are:

AriaNG UI: http://127.0.0.1/ui/
File Browser: http://127.0.0.1

Please pull the latest version docker image to have this feature, cheers. More information please refer https://github.com/wahyd4/aria2-ariang-docker/pull/23
