### ISSUE TITLE
The latest File Browse already has shared link management

### ISSUE THREAD

**Issue by gexiaopeng** [wahyd4/aria2-ariang-docker#151]
The latest File Browse already has shared link management，hope your File Browse can also be updated to the latest version

https://github.com/filebrowser/filebrowser/issues/1298

**Comment by wahyd4** [comment]
Hi @gexiaopeng, the latest docker image is using https://github.com/filebrowser/filebrowser/releases/tag/v2.11.0 which has the feature you mentioned. Please re-pull the latest docker image.
<img width="914" alt="Screen Shot 2021-02-26 at 9 01 28 pm" src="https://user-images.githubusercontent.com/836576/109286390-468c3580-7876-11eb-976d-9238bf23dbe0.png">

**Comment by gexiaopeng** [comment]
but docker  Aria2  File Manager no shared link management

https://registry.hub.docker.com/r/wahyd4/aria2-ui/
