### ISSUE TITLE
Docker Aria2 File Manager does not have shared link management

### ISSUE THREAD

**Issue by gexiaopeng** [wahyd4/aria2-ariang-docker#152]
Docker Aria2 File Manager（File Browser） does not have shared link management

https://registry.hub.docker.com/r/wahyd4/aria2-ui/

**Comment by wahyd4** [comment]
As you can see we are using the latest version of filebrowser which is v2.11.0. https://github.com/wahyd4/aria2-ariang-docker/blob/14a3ad5e538541fe81e9272547670eb9d32efc77/install.sh#L6

And the latest version of filebrowser https://github.com/filebrowser/filebrowser/releases/tag/v2.11.0

Anyway, please take a screenshot of the filebrowser you are running and share the sha256. 

**Remember manually run `docker pull wahyd4/aria2-ui:latest` to pull the latest version of the docker image.**

**Comment by gexiaopeng** [comment]
After I deleted aria2 and reinstalled it in docker, the File Browser version was 2.11.0, and shared links were also managed.
