### ISSUE TITLE
请问如何实现视频播放功能？

### ISSUE THREAD

**Issue by alexazhou** [wahyd4/aria2-ariang-docker#16]
文档中描述视频播放由 fileManager 提供，但是在 fileManager 中并没有找到这个功能，是需要另外配置么？

**Comment by wahyd4** [comment]
It's provided by default. You just need to double click the video then the player will come out and start playing.

Just make sure the file format is a normal video file format, .e.g. `mp4`.

Also there are some public test videos you can test with: 
https://gist.github.com/jsturgis/3b19447b304616f18657


![image](https://user-images.githubusercontent.com/836576/52092906-65735b80-260d-11e9-9435-fd30add0350e.png)

**Comment by alexazhou** [comment]
That's right, I play video success on web browser, I can't do it before because my video file was a .mkv file. 

Thank you!
