### ISSUE TITLE
raspberrypi start error

### ISSUE THREAD

**Issue by cgnq** [wahyd4/aria2-ariang-docker#162]
>   -p 8088:80 \
>   -p 443:443 \
>   -e PUID=1000 \
>   -e PGID=1000 \
>   wahyd4/aria2-ui
**** update uid and gid to 1000:1000 ****
usermod: no changes
**** give caddy permissions to use low ports ****
forego        | starting filebrowser.1 on port 5000
forego        | starting caddy.1 on port 5100
forego        | starting aria2c.1 on port 5300
forego        | starting rclone.1 on port 5600
caddy.1       | Run aria2c and ariaNG
caddy.1       | Using caddy without Basic Auth
rclone.1      | Start Rclone, please make sure you can connect to Github website. if not, please set docker env ENABLE_RCLONE=false
filebrowser.1 | 2021/05/16 04:24:56 No config file used
caddy.1       | {"level":"info","ts":1621139096.3881986,"logger":"automigrate","msg":"beginning one-time data directory migration","old_dir":"/root/.local/share/caddy","new_dir":"/app/.caddy/data/caddy","details":"https://github.com/caddyserver/caddy/issues/2955"}
caddy.1       | {"level":"error","ts":1621139096.3900313,"logger":"automigrate","msg":"new data directory already exists; skipping auto-migration as conservative safety measure - follow link for instructions","old_dir":"/root/.local/share/caddy","new_dir":"/app/.caddy/data/caddy","instructions":"https://github.com/caddyserver/caddy/issues/2955#issuecomment-570000333","error":"rename /root/.local/share/caddy /app/.caddy/data/caddy: permission denied"}
caddy.1       | {"level":"info","ts":1621139096.3910618,"logger":"automigrate","msg":"successfully completed one-time migration of data directory","old_dir":"/root/.local/share/caddy","new_dir":"/app/.caddy/data/caddy","details":"https://github.com/caddyserver/caddy/issues/2955"}
caddy.1       | {"level":"info","ts":1621139096.3929927,"msg":"using provided configuration","config_file":"/usr/local/caddy/Caddyfile","config_adapter":"caddyfile"}
aria2c.1      | Start aria2 with standard mode
caddy.1       | {"level":"info","ts":1621139096.413458,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
caddy.1       | {"level":"info","ts":1621139096.415149,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x2e0a190"}
caddy.1       | {"level":"info","ts":1621139096.4158251,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
caddy.1       | {"level":"info","ts":1621139096.4241815,"logger":"tls","msg":"cleaned up storage units"}
caddy.1       | {"level":"info","ts":1621139096.4264264,"msg":"autosaved config","file":"/app/.caddy/config/caddy/autosave.json"}
caddy.1       | {"level":"info","ts":1621139096.4269488,"msg":"serving initial configuration"}
aria2c.1      | /app/aria2c.sh: line 21:    54 Segmentation fault      (core dumped) /usr/bin/aria2c --conf-path="/app/conf/aria2.conf" --enable-rpc --rpc-listen-all
forego        | sending SIGTERM to filebrowser.1
forego        | sending SIGTERM to caddy.1
forego        | sending SIGTERM to rclone.1
caddy.1       | {"level":"info","ts":1621139096.500228,"msg":"shutting down apps then terminating","signal":"SIGTERM"}
caddy.1       | {"level":"info","ts":1621139097.001086,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0x2e0a190"}
caddy.1       | {"level":"info","ts":1621139097.5017436,"logger":"admin","msg":"stopped previous server"}
caddy.1       | {"level":"info","ts":1621139097.5018811,"msg":"shutdown done","signal":"SIGTERM"}

**Comment by wahyd4** [comment]
Hi @cgnq which Operating system you are using? Can you try to run the container with ubuntu instead of Pi lite?

 Looks like the error is related to that base on the log`aria2c.1 | /app/aria2c.sh: line 21: 54 Segmentation fault (core dumped) /usr/bin/aria2c --conf-path="/app/conf/aria2.conf" --enable-rpc --rpc-listen-all`

There's something you probably get some benefits from https://github.com/wahyd4/aria2-ariang-docker/issues/155

**Comment by cgnq** [comment]
just use 
`docker run --name aria -itd -p 8088:80 -v /home/pi/aria2/config/aria2.conf:/app/conf/aria2.conf  --privileged=true     wahyd4/aria2-ui`
从网上找个aria2.conf，替换掉默认的
