### ISSUE TITLE
raspberry 3B buster Lite caddy Exec format error

### ISSUE THREAD

**Issue by chu-0** [wahyd4/aria2-ariang-docker#167]
## Please try to use English to describe your question or issue.

**Describe the bug**
image tag: arm32

**Screenshots**
**** update uid and gid to 1000:1000 ****
usermod: no changes
**** give caddy permissions to use low ports ****
forego        | starting filebrowser.1 on port 5000
forego        | starting caddy.1 on port 5100
forego        | starting aria2c.1 on port 5300
forego        | starting rclone.1 on port 5600
caddy.1       | Run aria2c and ariaNG
caddy.1       | Using caddy without Basic Auth
rclone.1      | Start Rclone
caddy.1       | /app/caddy.sh: line 17: /usr/local/bin/caddy: cannot execute binary file: Exec format error
forego        | sending SIGTERM to filebrowser.1
forego        | sending SIGTERM to rclone.1
forego        | sending SIGTERM to aria2c.1

**Comment by wahyd4** [comment]
Hi @chu-0 this could be an os related issue, if you are using Pi OS, please take a look at https://github.com/wahyd4/aria2-ariang-docker/issues/155

**Comment by wahyd4** [comment]
Close it due to no further feedback
