### ISSUE TITLE
可以增加下载任务完成后自动上传网盘吗

### ISSUE THREAD

**Issue by jzysl123** [wahyd4/aria2-ariang-docker#170]
比如
https://github.com/P3TERX/aria2.conf
这里的upload.sh关联起来

文件上传脚本。在下载完成后执行(on-download-complete)，自动调用 RCLONE 上传(move)下载完成的文件到网盘，并自动清理控制文件(*.aria2)、种子文件(*.torrent)和空目录。（默认不启用）

**Comment by wahyd4** [comment]
HI @jzysl123 you can mount your custom aria2 config file into the container, you don't have to use the default config file.
