### ISSUE TITLE
已无法部署heroku

### ISSUE THREAD

**Issue by 362227** [wahyd4/aria2-ariang-docker#178]
https://bin.equinox.io/c/ekMN3bCZFUn/forego-stable-linux-amd64.tgz 失效了

wget -N https://bin.equinox.io/c/ekMN3bCZFUn/forego-stable-linux-amd64.tgz
--2021-10-12 09:53:28--  https://bin.equinox.io/c/ekMN3bCZFUn/forego-stable-linux-amd64.tgz
Resolving bin.equinox.io (bin.equinox.io)... 18.205.222.128, 52.202.168.65, 54.161.241.46, ...
Connecting to bin.equinox.io (bin.equinox.io)|18.205.222.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

**Comment by wahyd4** [comment]
Issue closed as no further updates
