### ISSUE TITLE
最新的AriaNg已经支持了BT种子文件筛选下载，能更新下吗？

### ISSUE THREAD

**Issue by xiaobebe** [wahyd4/aria2-ariang-docker#18]
最新的AriaNg已经支持了BT种子文件筛选下载，能更新下吗？

https://github.com/mayswind/AriaNg/issues/66

**Comment by wahyd4** [comment]
Have you confirmed the AriaNg version embedded in Docker image doesn't support?
The feature was actually released in last Oct, I assumed it should be already added by me to this docker image.

Please confirm this and upload a screenshot.

**Comment by wahyd4** [comment]
I am going to close this issue since there is no further feedback
