### ISSUE TITLE
Could not mount 

### ISSUE THREAD

**Issue by streamsaw** [wahyd4/aria2-ariang-docker#183]
**Describe the bug**
Hello,
I installed on Heroku and on VPS 
Everything seems working on Both - I have added remote cloud using rClone its working i can see files / upload & delete.
I tried to mount but failed.

I added a remote i.e gd1 and i tried to to mount i checked all options (enabled deamon)  tried 100 ways but i am not sure about Mount Point path.

Heroku: i used Mount point /app/fuse and /app/cloud & /cloud/data/gd1 ( with and without a / at end and begening)
VPS: i used Mount point to cloud/Folder /cloud -- aslo here i created a folder with 777 permession SEED and used this folder as mount its not working.

**To Reproduce**
Errors : Error creting mount: Request failed with status code 500

**Comment by wahyd4** [comment]
Hi @streamsawI'm not sure if I have fully understood you.

For Heroku, it doesn't support mount folders, please check https://devcenter.heroku.com/articles/container-registry-and-runtime#unsupported-dockerfile-commands for more details.

About the VPS, can you elaborate a bit more about what are you trying to achieve? And paste the steps/commands you have done to do it?

**Comment by liang-x-j** [comment]
sorry to bother you .after 2hours  I finally installed your project  to my vps and conneted rclone to my ondrive sucessfully  using command line :rclone config. but t it didnot upload the file which i downloaded to my ondrive. 
can you help me ,thanks

**Comment by wahyd4** [comment]
@streamsaw  @liang-x-j please check the latest version which supports auto uploading.
