### ISSUE TITLE
ARIA2_EXTERNAL_PORT seems do not make effect.

### ISSUE THREAD

**Issue by ashesofdream** [wahyd4/aria2-ariang-docker#185]
I run the docker behind the nginx  . I can access the aria2ng webite, but it always show that it is not connectd.
I have try to add config  of ARIA2_EXTERNAL_PORT , but it seems  make no sense.
this is my config

version: "3.5"
services:
  aria2-ui:
    restart: unless-stopped
    image: wahyd4/aria2-ui:latest
    environment:
      - ENABLE_AUTH=true
      - ARIA2_USER=xxxxxxx
      - ARIA2_PWD=xxxxxxxx
      - ARIA2_EXTERNAL_PORT=6800
    ports:
      - "23337:80"  
    volumes:
      - ./data:/data

![屏幕截图 2021-12-05 204146](https://user-images.githubusercontent.com/53961395/144747019-a6b17822-f381-486c-adcd-5a2728075507.png)

how could i fix it.

**Comment by ashesofdream** [comment]
i have solve it

**Comment by Evayangelion** [comment]
> i have solve it

sorry for bothering, I have met the same situation, wondering how u solved it.
