### ISSUE TITLE
How to enable cloudflare SSL to custom domain in Heroku?

### ISSUE THREAD

**Issue by drawndown** [wahyd4/aria2-ariang-docker#188]
HTTPS doesn't work when I change to a custom domain on Heroku. The HTTP site loads just fine though. How to fix this? I'm using cloudflare SSL.

**Comment by wahyd4** [comment]
I @drawndown Heroku has a lot of limitations in terms of running containers, this Cloudflare SSL feature is out of the scope of this project, please just use the Heroku provided HTTPS which should be good enough.
