### ISSUE TITLE
RPC_SECRET参数不起作用

### ISSUE THREAD

**Issue by netweaver** [wahyd4/aria2-ariang-docker#189]
yarm文件里RPC_SECRET参数不起作用， 在ariaNg中只要填写了ip、端口， 无需填写rpc secret token或随便填写都能连接

**Comment by rbforelle** [comment]
自己在aria2.conf里设置一下`rpc-secret=`就行了

**Comment by wahyd4** [comment]
Hi @netweaver  according to the code, you have to enable `ARIA2_SSL`  to enable `RPC_SECRET` feature, only setting `RPC_SECRET` doesn't work.

please check the source code here https://github.com/wahyd4/aria2-ariang-docker/blob/a8db9193f813b780681c9322f70352e4e220b61e/aria2c.sh#L7-L21 for more details.

**Comment by netweaver** [comment]
为何将rpc_secret和  secure捆绑啊？ 两者没有什么关系的，不想走SSL呢

**Comment by netweaver** [comment]
而且一般不会在这里做SSL，会在nginx等反代上做

**Comment by wahyd4** [comment]
Hi @netweaver now you can just set `rpc_secret` please check the readme for more details

**Comment by netweaver** [comment]
@wahyd4 thankyou
