### ISSUE TITLE
I see ads randomly opened when i click on the buttons on http mode webui

### ISSUE THREAD

**Issue by abhinavisgood** [wahyd4/aria2-ariang-docker#190]
I see ads randomly po when i click on the buttons on http mode  mode webui , please clear it that why did you do this

**Comment by wahyd4** [comment]
Hi @abhinavisgood  there shouldn't be any ads added by me, you can search from the codebase, this project is fully open source.

Also, please share more information about the ads you mentioned, including URL, screenshot, HTML source code and docker command you ran.

**Comment by wahyd4** [comment]
Hi @abhinavisgood  I will close this issue now given no further feedback has been provided, but feel free to provide more evidence on this later on.
