### ISSUE TITLE
Filebrowser DB Reset

### ISSUE THREAD

**Issue by capriciousduck** [wahyd4/aria2-ariang-docker#193]
When heroku dyno restarts the filebrowser wipes login credentials.

**Comment by wahyd4** [comment]
Hi @capriciousduck this is the reality of using Heroku, due to it doesn't support mount files, so you can't persist any configuration changes you made to FileBrowser.

**Comment by capriciousduck** [comment]
Does that apply to rclone as well?

**Comment by capriciousduck** [comment]
Is it possible to set filebrowser password to something else right before deployment? 

Moreover, does filebrowser support resumable downloads?

**Comment by wahyd4** [comment]
> Is it possible to set filebrowser password to something else right before deployment?
Not now.
> Moreover, does filebrowser support resumable downloads?
You can go to the GitHub repo page of filebrowser to ask for help on this question.
