### ISSUE TITLE
配置好了rclone，可以自动上传到onedrive吗。

### ISSUE THREAD

**Issue by liang-x-j** [wahyd4/aria2-ariang-docker#195]
是否有这个功能，
谢谢。

**Comment by wahyd4** [comment]
Hi @liang-x-j as long as Rclone support it, then you will get it from this docker image. We didn't change anything of Rclone in this Docker image.
So I will close this issue now, given this is a Rclone question.

**Comment by jzysl423** [comment]
这个并没有有自动上传的功能
这个功能还有有需求的  希望可以写个自动上传的脚本
 这个只有个例子 实际上大部人还是不会  希望有个写好的

**Comment by liang-x-j** [comment]
rclone 连接onedrive的功能不很稳定。莫名其妙的需要重新配置，有一个更好的https://github.com/MoeClub/OneList/tree/master/Rewrite,w 可以自动上传，也特别稳定。
建议WAHYD4 大佬换成这个。
