### ISSUE TITLE
無法配置 rclone

### ISSUE THREAD

**Issue by changchichung** [wahyd4/aria2-ariang-docker#196]
我在一台新的VPS 上跑了這個docker 
要配置rclone 時，不管是哪個provider 都會發生錯誤
在第一次設定時，會看到有一個提示訊息說( a new page wll open xxxxxxx) 閃一下就不見了
接下來就只會出現 500 error
操作過程如影片
https://transfer.sh/I4RAwT/simplescreenrecorder-2022-02-25_11.48.44.mp4

請問這個該怎麼處理？還是需要提供什麼其他log ??

**Comment by wahyd4** [comment]
Hi @changchichung  it's been coverd in the readme FAQ part, you should choose `configure rclone on a headless machine,` as it can't open any web pages from the terminal.
Can please check out https://github.com/wahyd4/aria2-ariang-docker/issues/118

**Comment by changchichung** [comment]
I'm sorry , there's no rclone part in docker-compose repo ( the chinese one ).
I will configure rclone in the container.
