### ISSUE TITLE
aria2c logging is too large

### ISSUE THREAD

**Issue by letssudormrf** [wahyd4/aria2-ariang-docker#2]
The aria2 conf file is written

> # General Options
> log=/var/log/aria2.log
> log-level=info

The level of info is meaningless, 
it will waste the disk space(it was take more 30GiB during download bt) 
and disk I/O for logging. 

It had better to change to null or error to reduce the disk space. 

How about the following suggestion? @wahyd4 

Change
> log=/var/log/aria2.log -> log=

Or

> log-level=info -> log-level=error

Reference: 
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-log-level

**Comment by wahyd4** [comment]
Thanks for your suggestion, you are right. Those info logs should not so important, and I have made the default log level to error now. 

Cheers!
