### ISSUE TITLE
ipv6导致速度为0

### ISSUE THREAD

**Issue by com3345** [wahyd4/aria2-ariang-docker#20]
页面上下bt一直是0，去后台看日志
![image](https://user-images.githubusercontent.com/11958810/54091053-3abbb600-43b6-11e9-91c2-9d01270f399c.png)

导致所有的bt下载速度都是0

一番搜索发现 在直接在容器内加上`aria2c --disable-ipv6=true`就能成功，但是ariang页面上默认就是关闭了ipv6但是是不起作用的。
![image](https://user-images.githubusercontent.com/11958810/54091186-f3362980-43b7-11e9-9201-a3067029bace.png)

我尝试着在aria2c.conf内添加`disable-ipv6=true`并重启了docker和containner，但并没有用

**Comment by wahyd4** [comment]
How did you apply the command `aria2c --disable-ipv6=true` to the container? By environment variables in the docker compose?

**Comment by com3345** [comment]
> How did you apply the command `aria2c --disable-ipv6=true` to the container? By environment variables in the docker compose?

Nope, I just ran `aria2c` command directly in the container's command line (which I think `/bin/aria2c` was run in fact), such as  `aria2c --disable-ipv6=true xxxx.torrent` and it worked well. But I don't know how to get the `--disable-ipv6=true` work when things come to Ariang side.

I tried two ways:

### 1, Adding the option to aria2.conf explicitly.

    # aria2.conf in /root/conf/aria2.conf
    ....
    disable-ipv6=true
    ....

then restarts, still no speed when downloading BT task sent from Ariang 

### 2, Adding the option to aria2c.sh explicitly

Actually,  I also added `--disable-ipv6` option to `/root/aria2c.sh` as follows:

    ....
    if [ "$SSL" = "true" ]; then
    echo "Start aria2 with secure config"

    /usr/bin/aria2c --conf-path="/root/conf/aria2.conf" -D  \
    --enable-rpc --rpc-listen-all  \
    --rpc-certificate=/root/conf/key/aria2.crt \
    --rpc-private-key=/root/conf/key/aria2.key \
    --rpc-secret="$RPC_SECRET" --rpc-secure \
    --disable-ipv6=true \                # inserted here...
    && caddy -quic --conf ${CADDY_FILE}

    else
    echo "Start aria2 with standard mode"
    /usr/bin/aria2c --conf-path="/root/conf/aria2.conf" -D \
    --enable-rpc --rpc-listen-all \
    --disable-ipv6=true \                # ....and here
    && caddy -quic --conf ${CADDY_FILE}
    fi

then restarted the container and the same error in first try

**Comment by wahyd4** [comment]
Sorry, I couldn't reproduce the issue you mentioned, can you provide the bt torrent file you used?

**Comment by wahyd4** [comment]
Try the latest docker image, it should work now.
```bash
docker pull wahyd4/aria2-ui:latest
```
