### ISSUE TITLE
deployed on heroku, the app is up and running; but  can't find rclone features/interface at all.

### ISSUE THREAD

**Issue by mobilelifeful** [wahyd4/aria2-ariang-docker#201]
## Please try to use English to describe your question or issue.

**Describe the bug**

deployed on heroku through [this](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fwahyd4%2Faria2-ariang-docker&template=https%3A%2F%2Fgithub.com%2Fwahyd4%2Faria2-ariang-docker%2Ftree%2Fmaster), the app is up and running; but can't find Rclone feature at all.

**To Reproduce**
1. Go to [link](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fwahyd4%2Faria2-ariang-docker&template=https%3A%2F%2Fgithub.com%2Fwahyd4%2Faria2-ariang-docker%2Ftree%2Fmaster)
2. Filled out as
https://user-images.githubusercontent.com/30308165/155456381-3d972094-b3a5-4d65-918a-2ab9c11f7673.png
 3. login on heroku.
 
 
**Expected behavior**
Rcloen web interface to upload the downloaded content. 

**Screenshots**

**Comment by wahyd4** [comment]
@mobilelifeful  Please paste the logs from Heroku.

**Comment by wahyd4** [comment]
Closing this issue now due to no further updates.
