### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by AmirulAndalib** [wahyd4/aria2-ariang-docker#206]
pls add qbittorrent + ariang + filebrowser + rclone docker with heroku support ...i think it would be awesome to have a repo like that thank you

**Comment by wahyd4** [comment]
Hi @AmirulAndalib this repo has already been banned from Heroku already https://github.com/wahyd4/aria2-ariang-docker/issues/204
So I wouldn't spend any more time on Heroku related features unless there is some positive feedback from Heroku. You can clone this repo and deploy it with your own modified code.

**Comment by AmirulAndalib** [comment]
> Hi @AmirulAndalib this repo has already been banned from Heroku already #204 So I wouldn't spend any more time on Heroku related features unless there is some positive feedback from Heroku. You can clone this repo and deploy it with your own modified code.

Just don't put heroku button But keep it's stuff heroku won't reply
