### ISSUE TITLE
网络模式只能用host

### ISSUE THREAD

**Issue by fl20002** [wahyd4/aria2-ariang-docker#21]
已经连接正确，添加下载任务就提示错误

Exception: [AbstractCommand.cc:351] errorCode=1 URI=http://dlied5.myapp.com/myapp/1104466820/sgame/2017_com.tencent.tmgp.sgame_h177_1.42.1.6_a6157f.apk
  -> [SocketCore.cc:437] errorCode=1 Failed to resolve the hostname 58.216.96.50, cause: System error

 bridge 模式  80：80       6800：6800  

但是用host 模式  下载正常  

其他参数没变

**Comment by com3345** [comment]
老哥我感觉你的错误跟我一样？能提供更多的log吗？或者你看下我的log #20 ，是不是上面也提示ipv6的error？

**Comment by fl20002** [comment]
2019-03-14 15:50:35.264230 [ERROR] [HttpListenCommand.cc:112] IPv6 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: System error
2019-03-14 15:50:52.055572 [ERROR] [AbstractCommand.cc:351] CUID#12 - Download aborted. URI=http://dlied5.myapp.com/myapp/1104466820/sgame/2017_com.tencent.tmgp.sgame_h177_1.42.1.6_a6157f.apk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=http://dlied5.myapp.com/myapp/1104466820/sgame/2017_com.tencent.tmgp.sgame_h177_1.42.1.6_a6157f.apk
  -> [SocketCore.cc:437] errorCode=1 Failed to resolve the hostname 58.216.96.50, cause: System error

确实有  

我用host模式就没问题

**Comment by wahyd4** [comment]
Hi guys, According to the github issue from aria2c https://github.com/aria2/aria2/issues/1309, you can set the property in `aria2.conf` to `disable-ipv6=true` to solve this.

Also, I will release a new docker image with updated config file very soon.

**Comment by wahyd4** [comment]
Please pull the `latest` tag docker image, it will work.

**Comment by fl20002** [comment]
感谢  已经没问题了
