### ISSUE TITLE
aria2-sample-hook.sh

### ISSUE THREAD

**Issue by zephyr-y** [wahyd4/aria2-ariang-docker#213]
没有找到rclone自动上传的代码，请问作者有计划提供这块功能么？

**Comment by wy580477** [comment]
我按作者思路写了一个yt-dlp+aria2自动上传rclone的容器。

https://github.com/wy580477/Aria2-AIO-Container

**Comment by wahyd4** [comment]
Hi friends, please try our latest release which supports auto-upload when you have env `RCLONE_AUTO_UPLOAD_PROVIDER` provided. Feedback is high appreciated.
