### ISSUE TITLE
Not able to map "conf" in Synology Docker

### ISSUE THREAD

**Issue by earthruby** [wahyd4/aria2-ariang-docker#218]
Hi,

I downloaded the latest version in Synology Docker, however, whenever I map the "/app/conf" folder, the container stops with this error message:
Docker container ARIA2_UI stopped unexpectedly. Go to Docker for more information.

But if I delete this entry, just keeping the "/data" folder, it works.

I have manually placed the "aria2.session and aria2.conf" files, but still doesn't work. 

May I know how to solve this problem?

thanks!

**Comment by wahyd4** [comment]
Hi @earthruby can you share the full logs you get from Synology as well as the screenshot of the full configuration?
