### ISSUE TITLE
no matching manifest for linux/s390x

### ISSUE THREAD

**Issue by kitkw** [wahyd4/aria2-ariang-docker#220]
latest: Pulling from wahyd4/aria2-ui
no matching manifest for linux/s390x in the manifest list entries

**Comment by wahyd4** [comment]
Hi @kitkw thanks for using this Docker image, and looks like you are [IBM Z](https://en.wikipedia.org/wiki/Linux_on_IBM_Z) machines, unfortunately, there is no plan to support this type of CPU architecture.

Please use x64 or ARM CPU platforms.
