### ISSUE TITLE
建议可以升级一下filebrowser的js提高在线播放格式的支持

### ISSUE THREAD

**Issue by xratzh** [wahyd4/aria2-ariang-docker#223]
原版本的fb对目前越来越新的视频文件格式支持不太友好。播放界面也比较单调。
国内有荒野无灯的加强版。
如果大佬有空闲和兴趣，可以考虑集成更新一下。
再次感谢老乡的集成，一键部署docker后，很好用。

**Comment by wahyd4** [comment]
Can you share the link of "荒野无灯的加强版" you are talking about? Happy to have a look.

**Comment by xratzh** [comment]
https://registry.hub.docker.com/r/80x86/filebrowser
我只知道他的docker仓库，有兴趣的话可以看看，哈哈。
不过很久没有update了。
BTW，新年快乐！

**Comment by wahyd4** [comment]
Hi @xratzh I think it wouldn't work here
