### ISSUE TITLE
Better to provide a script to create empty files which are needed when volumes are configured

### ISSUE THREAD

**Issue by tan-wei** [wahyd4/aria2-ariang-docker#228]
First, thanks this great project. I've successfully launched the project in Synology NAS.

However, if I were not familiar with Docker, I will hard to use it. The project supports volumes, but if volumes in */app* are configured, we should manually create some files before we create the image, such as:
  - aria2.conf (not empty but could use a default one)
  - aria2.session
  - filebrowser.db

So it is better to provide an automatic script to create these files. It will make the deploying process easy. The script will be executed at the first time run the image.

Just an advise. Thanks for all these.

**Comment by wahyd4** [comment]
Hi @tan-wei thanks for raising this, it is something we can make the image better.  If you don't `aria2.conf` existed, it is not recommended to mount the entire folder `/app/conf`. 

Currently, I can't just generate `aria2.conf` file when detect the mounted folder doesn't have this file, becuase there are more files under this folder https://github.com/wahyd4/aria2-ariang-docker/tree/master/conf, I would recommend you first mount your drive to another folder and exec into the container and copy `/app/conf` to your drive, then update the mount point to `/app/conf` again.

Given so, I will close this ticket now, but please feel free to submit PR to improve it.
