### ISSUE TITLE
armv7l Armbian 23.05.0-trunk Bullseye 运行失败

### ISSUE THREAD

**Issue by che246** [wahyd4/aria2-ariang-docker#234]
forego                  | sending SIGTERM to filebrowser.1
filebrowser.1           | 2023/05/03 18:45:54 Caught signal terminated: shutting down.
filebrowser.1           | 2023/05/03 18:45:54 accept tcp 127.0.0.1:8080: use of closed network connection
[INFO] Update uid and gid to 1000:1000
usermod: no changes
[INFO] Run chown against app related folders and user 1000
[INFO] Give caddy permissions to use low ports
forego                  | starting caddy.1 on port 5000
forego                  | starting filebrowser.1 on port 5100
forego                  | starting aria2c.1 on port 5300
forego                  | starting rclone.1 on port 5600
forego                  | starting newer_version_checker.1 on port 6000
caddy.1                 | [INFO] Run aria2c and ariaNG
caddy.1                 | [INFO] Generate basic auth password for caddy
rclone.1                | [INFO] Start Rclone, please make sure you can connect to Github website. if not, please set docker env ENABLE_RCLONE=false
filebrowser.1           | 2023/05/03 18:46:56 No config file used
filebrowser.1           | 2023/05/03 18:46:56 Listening on 127.0.0.1:8080
aria2c.1                | [INFO] Start aria2 with standard mode
aria2c.1                | /app/aria2c.sh: line 26:    59 Segmentation fault      (core dumped) /usr/bin/aria2c --conf-path="/app/conf/aria2.conf" --enable-rpc --rpc-listen-all
forego                  | sending SIGTERM to caddy.1
forego                  | sending SIGTERM to newer_version_checker.1
forego                  | sending SIGTERM to rclone.1
forego                  | sending SIGTERM to filebrowser.1
filebrowser.1           | 2023/05/03 18:46:58 Caught signal terminated: shutting down.
[INFO] Update uid and gid to 1000:1000
usermod: no changes
[INFO] Run chown against app related folders and user 1000
[INFO] Give caddy permissions to use low ports
forego                  | starting caddy.1 on port 5000
forego                  | starting filebrowser.1 on port 5100
forego                  | starting aria2c.1 on port 5300
forego                  | starting rclone.1 on port 5600
forego                  | starting newer_version_checker.1 on port 6000
caddy.1                 | [INFO] Run aria2c and ariaNG
caddy.1                 | [INFO] Generate basic auth password for caddy
rclone.1                | [INFO] Start Rclone, please make sure you can connect to Github website. if not, please set docker env ENABLE_RCLONE=false
aria2c.1                | [INFO] Start aria2 with standard mode
aria2c.1                | /app/aria2c.sh: line 26:    56 Segmentation fault      (core dumped) /usr/bin/aria2c --conf-path="/app/conf/aria2.conf" --enable-rpc --rpc-listen-all
filebrowser.1           | 2023/05/03 18:48:00 No config file used
filebrowser.1           | 2023/05/03 18:48:00 Listening on 127.0.0.1:8080
forego                  | sending SIGTERM to caddy.1
forego                  | sending SIGTERM to newer_version_checker.1
forego                  | sending SIGTERM to rclone.1
forego                  | sending SIGTERM to filebrowser.1
filebrowser.1           | 2023/05/03 18:48:00 Caught signal terminated: shutting down.
filebrowser.1           | 2023/05/03 18:48:00 accept tcp 127.0.0.1:8080: use of closed network connection

## Please try to use English to describe your question or issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by che246** [comment]
docker run -d --name aria2-ui -p 80:80 wahyd4/aria2-ui

**Comment by wahyd4** [comment]
Hi @che246 looks like `aria2c` failed to run on your platform

**Comment by che246** [comment]
> 你好@che246看起来`aria2c`无法在您的平台上运行
> 
> ```
>  /app/aria2c.sh: line 26: 56 Segmentation fault (core dumped) /usr/bin/aria2c --conf-path="/app/conf/aria2.conf" --enable-rpc --rpc-listen-all
> ```
> 
> 你可以试试`docker run -d --name aria2-ui -p 8000:80 wahyd4/aria2-ui:arm32`哪个是旧版本，看看它是否适合你？


docker run -d --name aria2-ui -p 8000:80 wahyd4/aria2-ui:arm32

**** update uid and gid to 1000:1000 ****
usermod: no changes
**** give caddy permissions to use low ports ****
forego        | starting filebrowser.1 on port 5000
forego        | starting caddy.1 on port 5100
forego        | starting aria2c.1 on port 5300
forego        | starting rclone.1 on port 5600
caddy.1       | Run aria2c and ariaNG
caddy.1       | Using caddy without Basic Auth
rclone.1      | Start Rclone
caddy.1       | /app/caddy.sh: line 17: /usr/local/bin/caddy: cannot execute binary file: Exec format error
forego        | sending SIGTERM to filebrowser.1
forego        | sending SIGTERM to rclone.1
forego        | sending SIGTERM to aria2c.1

**Comment by wahyd4** [comment]
Hi @che246, I have made some changes and switched to using Debian as the base image. Please try again and let me know if the issue you were experiencing still persists.
