### ISSUE TITLE
docker run -d --name aria2-ui -p 80:80 -p 443:443 -e DOMAIN=http://domainname.tld wahyd4/aria2-ui 

### ISSUE THREAD

**Issue by johnsmithodom** [wahyd4/aria2-ariang-docker#238]
## Please try to use English to describe your question or issue.
run this command with docker installed

`
docker run -d --name aria2-ui -p 80:80 -p 443:443 -e DOMAIN=https://domainname.tld wahyd4/aria2-ui 
`
**Describe the bug**
everything seems working, but aria2 is not connecting

`
`
c4bb5836d52b   wahyd4/aria2-ui   "./start.sh"   9 minutes ago   Up 8 minutes (healthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 6881/tcp   aria2-ui
`
te_ip":"127.0.0.1","remote_port":"49842","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/ping","headers":{"User-Agent":["curl/7.74.0"],"Accept":["*/*"]}},"user_id":"","duration":0.000005372,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1                 | {"level":"info","ts":1685891797.8227344,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"127.0.0.1","remote_port":"57076","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/ping","headers":{"Accept":["*/*"],"User-Agent":["curl/7.74.0"]}},"user_id":"","duration":0.00000686,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1                 | {"level":"info","ts":1685891830.685484,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"127.0.0.1","remote_port":"35996","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/ping","headers":{"User-Agent":["curl/7.74.0"],"Accept":["*/*"]}},"user_id":"","duration":0.000007257,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1                 | {"level":"info","ts":1685891860.8728356,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"127.0.0.1","remote_port":"42314","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/ping","headers":{"User-Agent":["curl/7.74.0"],"Accept":["*/*"]}},"user_id":"","duration":0.000005411,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1                 | {"level":"info","ts":1685891892.4046726,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"127.0.0.1","remote_port":"49192","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/ping","headers":{"User-Agent":["curl/7.74.0"],"Accept":["*/*"]}},"user_id":"","duration":0.000007637,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1                 | {"level":"info","ts":1685891924.7122633,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"127.0.0.1","remote_port":"56772","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/ping","headers":{"User-Agent":["curl/7.74.0"],"Accept":["*/*"]}},"user_id":"","duration":0.000006028,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1                 | {"level":"info","ts":1685891954.894142,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"127.0.0.1","remote_port":"34812","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/ping","headers":{"User-Agent":["curl/7.74.0"],"Accept":["*/*"]}},"user_id":"","duration":0.000005673,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
`

**To Reproduce**
1. Go to 'vps'
2. Click on 'install docker'
3. Run command of
`docker run -d --name aria2-ui -p 80:80 -p 443:443 -e DOMAIN=http://domainname.tld wahyd4/aria2-ui`  
![image](https://github.com/wahyd4/aria2-ariang-docker/assets/120798996/d68ce44d-0dcc-4113-a04e-778384c6989c)

**Expected behavior**
![image](https://github.com/wahyd4/aria2-ariang-docker/assets/120798996/dea45b07-0bd9-422d-8411-e8b30b83d8ff)

**Screenshots**

**Comment by HsuJv** [comment]
+1 for me
I restore the last version wahyd4/aria2-ui:5.4.0 which works well.
Hope this would be helpful for you.

BRs.

**Comment by wahyd4** [comment]
Hi guys, sorry for the late reply. I just noticed this now, does this issue still exist?

**Comment by wahyd4** [comment]
HI @johnsmithodom @HsuJv what's the behaviour you saw? Did the container stop a while after? Or it's running but you can't access it?

**Comment by wahyd4** [comment]
Hi @HsuJv, unfortunately I can't re-produce the issue you mentioned, I don't have those `caddy access` logs that keep showing.
Can you share the full command you use, the OS and CPU platform etc?

**Comment by wahyd4** [comment]
@HsuJv And `/ping` access log does keep showing up every `30s`, given it's the [docker health check script](https://github.com/wahyd4/aria2-ariang-docker/blob/master/Dockerfile#L65-L66), which is to detect if your container is healthy.

I guess in your case, the logs actually mean the container is healthy.
Maybe also check the port you used to expose your service as well as the URL and port you used to access the service.

**Comment by HsuJv** [comment]
Hi @wahyd4,

With no idea I cannot reproduce the issue this time.
It seems everything goes well while last time the issue persisted even if I delete the old image and re-installed it from scratch.
I'm using docker-compose with a fixed compose file so it must be the same configuration during the two experiments.
Anyway I'll switch to the latest release and keep monitoring.

Will ping you if I see the issue again.

BRs.
