### ISSUE TITLE
访问地址问题

### ISSUE THREAD

**Issue by Code-Fight** [wahyd4/aria2-ariang-docker#27]
Aria2: http://yourip/ui/

如果不加最后的“/”
http://yourip/ui
这样访问，会丢失页面样式

是不是可以访问http://yourip/ui的时候 自动重定向一下

**Comment by wahyd4** [comment]
Thanks, it sounds promising. But the download script for Caddy server is currently broken which stops me building the Docker image, I will try it again soon.

**Comment by wahyd4** [comment]
I tried with either `rewrite` or `redir` in Caddy, but I couldn't make it work.
In Caddy and probably a widly common sense that `/ui` and `/ui/` means two different things. `/ui` means the ui page of the website, it's a single file. But the `/ui/` actually means navigate me to the ui folder.

But anyway, if you can make it work and make a pull request, I'm happy to apply it to the repo. 

Cheers.

**Comment by wahyd4** [comment]
This been solved in #37
