### ISSUE TITLE
群晖上docker安装，无法通过web访问ariaNg

### ISSUE THREAD

**Issue by ha7rock** [wahyd4/aria2-ariang-docker#32]
如题，日志都正常。file manager可以正常访问 

请问此为何故？

**Comment by wahyd4** [comment]
How do you expect that I can help you find out the issue but without providing enough information?
At least you should provide what's the URL you use when access AriaNg.
Also what's the `normal` log is? Please paste the log.

Last but not least, please spend some time search the issues and read the issue template before you create this issue. It probably can help you solve the issue and give you some basic thoughts what does a good issue should looks like.

I'm happy to help you solve any issues, but I really hope you can submit a `good` issue with enough details.

**Comment by ha7rock** [comment]
很抱歉，没把问题说明白。

不过的确是尝试了浏览过去的issues确认没类似问题才发问，再次抱歉。

通过群晖的docker安装最新版本。配置如下：

![I` M9 W2KNY(WFVT(TR%BS](https://user-images.githubusercontent.com/33951467/57862571-28814c80-782b-11e9-8aaa-b86c8f96fd2a.png)

![U0_MNO$SJE44NZ4M8(Z 7FM](https://user-images.githubusercontent.com/33951467/57862579-2d460080-782b-11e9-95ab-07c90600315a.png)

配置完成可以正常运行，file manager 通过 http://yourip:6888 可以正常访问使用。

而ariang则无法通过http://yourip:6443访问, chrome返回ERR_EMPTY_RESPONSE错误

但是aria2正常运行，测试了百度网盘助手可以正常添加并下载文件。

![)}~3RFV`)CJE~G}CW@ 8MJO](https://user-images.githubusercontent.com/33951467/57863595-f40e9000-782c-11e9-84e3-9052e48be571.png)

**Comment by wahyd4** [comment]
According to the Readme the AriaNg share the same port with file browser, so the correct URl should be `http://up:6888/ui/`

**Comment by ha7rock** [comment]
too ashamed…

thanks 😖

**Comment by GarrickLin** [comment]
找到这才知道。。。
