### ISSUE TITLE
可以用迅雷下载链接下载东西么，我放了迅雷怎么没法点击立即下载

### ISSUE THREAD

**Issue by liansghuaifan** [wahyd4/aria2-ariang-docker#4]

**Comment by wahyd4** [comment]
不支持迅雷下载，因为下载工具使用的是 Aria2c， 根据 Aria2c 官方文档其支持：

`It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink`

更多： https://aria2.github.io/

推荐的是使用 BT 或者磁力链接进行下载。
