### ISSUE TITLE
没有权限访问.You don't have permissions to access this.

### ISSUE THREAD

**Issue by longearshortail** [wahyd4/aria2-ariang-docker#46]
群晖的docker, 安装完成后进入file显示You don't have permissions to access this.

![image](https://user-images.githubusercontent.com/32356094/63944314-e3182080-caa3-11e9-847e-6efae5a87e86.png)

下载树莓派日志也显示没有权限

![image](https://user-images.githubusercontent.com/32356094/63944444-18247300-caa4-11e9-8ba9-34d53b36114c.png)

怎么开通权限?

**Comment by wahyd4** [comment]
You will need to specify the environment variables `GID` and `UID`, and those values are the user and the group have access to the folder to you mounted.  
The simplest way is to set the `UID` and `GID` to `root` user's `UID` and `GID`

**Comment by longearshortail** [comment]
> You will need to specify the environment variables `GID` and `UID`, and those values are the user and the group have access to the folder to you mounted.
> The simplest way is to set the `UID` and `GID` to `root` user's `UID` and `GID`

赞美大佬! 我试了admin的1024, 登陆用户名的1026, 最后用root的0终于有访问权限了, 再次感谢大佬.
