### ISSUE TITLE
chown破坏外挂文件系统权限信息

### ISSUE THREAD

**Issue by AtrisMio** [wahyd4/aria2-ariang-docker#48]
https://github.com/wahyd4/aria2-ariang-docker/blob/master/init.sh#L7-L8

这里会更改`/data`目录原本的权限信息

**Comment by wahyd4** [comment]
Thanks for reporting this, would you like to make a pull request to fix this? I would be very appreciated if you can make it happen.

**Comment by wahyd4** [comment]
A new version has been released
