### ISSUE TITLE
无法使用自己的配置文件

### ISSUE THREAD

**Issue by chocksyu** [wahyd4/aria2-ariang-docker#5]
您好！
请教个问题，我用群晖Docker搭建您的aria2，可正常使用。但是无法使用自己的.conf配置文件。也就是从docker内将配置文件/root/conf/aria2.conf映射到我指定的文件，AriaNg就无法连接（网页设置输入密码也无法连接），请问大神有解决办法吗？

**Comment by wahyd4** [comment]
请贴出你的运行命令 和 docker 容器的日志信息

**Comment by chocksyu** [comment]
![1](https://user-images.githubusercontent.com/30619889/39662588-9496c584-5096-11e8-88dc-396da42da0a3.jpg)
![2](https://user-images.githubusercontent.com/30619889/39662589-94fe6464-5096-11e8-9d5e-758f463f784a.jpg)

感谢您的快速回复，我是直接在群晖的docker里面进行的设置，之前也google了很久解决办法，在网上没有找到答案，还烦请您帮忙解答。如果还需要我提供其他信息烦请告知。谢谢

**Comment by wahyd4** [comment]
我感觉是配置文件没有成功映射，导致 aria2 没有运行， 你可以通过进入到 docke 容器终端，去查看下配置文件的目录下是否有你的文件。

**Comment by chocksyu** [comment]
![3](https://user-images.githubusercontent.com/30619889/39663392-4fdb65b2-50a5-11e8-9d1c-24f0d2899147.jpg)
![4](https://user-images.githubusercontent.com/30619889/39663396-5f5e0b20-50a5-11e8-9901-e8815abdbfc5.jpg)
您好！
第一张图是没有将配置文件映射到自己文件时的情况，有.conf文件存在
第二张图时将配置文件映射到自己文件的情况，没有了.conf文件
我刚刚又google了一下设法自己解决，实在没有找到解决办法，还是得麻烦您帮我看一下。谢谢

**Comment by wahyd4** [comment]
这就说明你配置的群晖上面的地址是错的，或者群晖禁止你访问那个目录。总之就是你配置的文件不能被docker找到

**Comment by chocksyu** [comment]
![5](https://user-images.githubusercontent.com/30619889/39663515-6295284e-50a7-11e8-8444-0163a4197461.jpg)
刚刚又重新检查了一遍，配置文件地址没问题，权限也开了。另外这个配置文件我之前在使用其他aria2映像的时候是可以正常使用的。好郁闷

**Comment by chocksyu** [comment]
同样挂在/downloads到/data 就是没问题的

**Comment by chocksyu** [comment]
如果直接挂在我的配置文件夹 /docker/conf/ 到 /root/conf/ 的话 日志会报错显示无法启动/root/conf/aria2c.sh

**Comment by wahyd4** [comment]
我看你的配置文件目录应该是/docker/aria2.conf吧

**Comment by chocksyu** [comment]
是的大神，后来把配置目录都改成/docker/aria2.conf了 不管是挂载/docker/aria2.conf 还是 /docker/aira2/config/aria2.conf 都不行

**Comment by wahyd4** [comment]
这个是因为你的配置文件问题，和本项目无关，你自己再尝试解决吧
