### ISSUE TITLE
ARM Deployment

### ISSUE THREAD

**Issue by capriciousduck** [wahyd4/aria2-ariang-docker#53]
Hi Junv,

I want to deploy this app on my RPi but I do not need the file browser. Any way to disable that?

Or should I build a custom docker image?

And can I use apache or nginx instead of Caddy?

**Comment by capriciousduck** [comment]
I am a beginner in programming so setting up apache or Nginx seems simple for me.

**Comment by wahyd4** [comment]
You can find and use some other similar Docker image if you only need a Docker image with aria2.
