### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by capriciousduck** [wahyd4/aria2-ariang-docker#55]
Junv I don't know if this is a relevant question: Is it possible to download files from google drive? 

I have seen some scripts output a URL to download using wget. Will you be able to integrate those scripts into this app?

**Comment by wahyd4** [comment]
I don't this is relevant. The main purpose of this docker image is providing a super easy way which is Docker for users to use aria2c, ariang and filebrowser all together. 
So adding any extra functionalities is not the scope of this project unless you can make a pull request to implement what you want.
