### ISSUE TITLE
filebrowser.1 | 2019/09/23 04:10:19 No config file used filebrowser.1 | 2019/09/23 04:10:19 the resource does not exist

### ISSUE THREAD

**Issue by hehh2001** [wahyd4/aria2-ariang-docker#56]
First of all, thank you very much for your project.
if  you   take      -v /app/a.db:/app/filebrowser.db \     
Unable to start properly
Log prompt　　filebrowser.1 | 2019/09/23 04:10:19 No config file used filebrowser.1 | 2019/09/23 04:10:19 the resource does not exist
but   I have this file in the corresponding mount directory
No way. I can't start until I remove this parameter.

Another problem is that it takes up too much space. My host root directory has been occupied (76G) after running for a week. Is there any way to reduce the occupancy? / The corresponding container files under var/lib/docker/overlay2 were deleted before the system started normally. I rebuilt it. What can I do to reduce the occupancy? My hard disk is not rich. Can I change my configuration file to solve this problem?

Thank you again for your work!!!!!!!!

**Comment by wahyd4** [comment]
Please follow the issue template to provide more information. 

For example, the docker command you run, the entire logs, your platform, Linux dist and so on...

**Comment by hehh2001** [comment]
docker run -d --name ariang \
  -p 80:80 \
  -p 443:443 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e ENABLE_AUTH=true \
  -e RPC_SECRET=Hello \
  -e DOMAIN=https://example.com \
  -e ARIA2_SSL=false \
  -e ARIA2_USER=user \
  -e ARIA2_PWD=pwd \
  -v /srv/media/downloads:/data \
  -v /srv/media/app/filebrowser.db:/app/filebrowser.db \
  -v /srv/media/app/conf/key:/app/conf/key \
  -v /srv/media/app/conf:/app/conf \
  wahyd4/aria2-ui

Cannot start after adding this parameter
-v /srv/media/app/filebrowser.db:/app/filebrowser.db \

docker  logs   
filebrowser.1 | 2019/09/23 04:10:19 No config file used filebrowser.1 |
filebrowser.1 | 2019/09/23 04:10:19 the resource does not

**Comment by wahyd4** [comment]
Do you have this file exists on your host `/srv/media/app/filebrowser.db`? This must be a file rather than a folder.

**Comment by hehh2001** [comment]
Yes, it's a file, not a folder.

**Comment by wahyd4** [comment]
> No way. I can't start until I remove this parameter.

What have you removed to make the command works?

**Comment by hehh2001** [comment]
The above problem is not serious. Can you help me reduce the disk usage? Look at my configuration file. Disk occupancy is a big problem. I don't want to make soft links to transfer the docker directory.

**Comment by hehh2001** [comment]
## 全局设置 ## ============================================================
# 日志
# General Options
log=/var/log/aria2.log
#You can set either debug, info, notice, warn or error.
#log-level=notice
log-level=error

# 下载位置, 默认: 当前启动位置
#dir=/PATH/Downloads
dir=data

## 进度保存相关 ##
# 从会话文件中读取下载任务
input-file=/app/conf/aria2.session

# 在Aria2退出时保存`错误/未完成`的下载任务到会话文件
save-session=/app/conf/aria2.session

# 定时保存会话, 0为退出时才保存, 需1.16.1以上版本, 默认:0
save-session-interval=60

#############
force-save=true

# 断点续传
continue=true

# 启用磁盘缓存, 0为禁用缓存, 需1.16以上版本, 默认:16M
#disk-cache=32M

# 文件预分配方式, 能有效降低磁盘碎片, 默认:prealloc
# 预分配所需时间: none < falloc ? trunc < prealloc
# falloc和trunc则需要文件系统和内核支持
# NTFS建议使用falloc, EXT3/4建议trunc, MAC 下需要注释此项
file-allocation=trunc

# 客户端伪装
user-agent=netdisk;5.2.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia
referer=http://pan.baidu.com/disk/home

# 禁用IPv6, 默认:false
disable-ipv6=true

# 其他
always-resume=true
check-integrity=true

## 下载位置 ## ============================================================
# 最大同时下载任务数, 运行时可修改, 默认:5
max-concurrent-downloads=5

# 同一服务器连接数, 添加时可指定, 默认:1
max-connection-per-server=5

# 最小文件分片大小, 添加时可指定, 取值范围1M -1024M, 默认:20M
# 假定size=10M, 文件为20MiB 则使用两个来源下载; 文件为15MiB 则使用一个来源下载
min-split-size=10M

# 单个任务最大线程数, 添加时可指定, 默认:5
split=10

# 整体下载速度限制, 运行时可修改, 默认:0
#max-overall-download-limit=0

# 单个任务下载速度限制, 默认:0
#max-download-limit=0

# 整体上传速度限制, 运行时可修改, 默认:0
#max-overall-upload-limit=0

# 单个任务上传速度限制, 默认:0
#max-upload-limit=0

## RPC设置 ## ============================================================
#用户名
#rpc-user=wlb

#密码
#rpc-passwd=85257591

#上面的认证方式不建议使用,建议使用下面的token方式
# 设置的RPC授权令牌, v1.18.4新增功能, 取代 --rpc-user 和 --rpc-passwd 选项
#rpc-secret=token
rpc-secure=false
 
#允许所有来源, web界面跨域权限需要
rpc-allow-origin-all=true

# 启用RPC, 默认:false
enable-rpc=true

# 事件轮询方式, 取值:[epoll, kqueue, port, poll, select], 不同系统默认值不同
#event-poll=select

# RPC监听端口, 端口被占用时可以修改, 默认:6800
#允许外部访问，false的话只监听本地端口
#rpc-listen-port=80
rpc-listen-all=true

# 在 RPC 服务中启用 SSL/TLS 加密时的证书文件,
# 使用 PEM 格式时，您必须通过 --rpc-private-key 指定私钥
#rpc-certificate=/path/to/certificate.pem

# 在 RPC 服务中启用 SSL/TLS 加密时的私钥文件
#rpc-private-key=/path/to/certificate.key

#########
pause=false

###############
#rpc-save-upload-metadata=true

## BT/PT下载相关 ## ============================================================
# 当下载的是一个种子(以.torrent结尾)时, 自动开始BT任务, 默认:true
#follow-torrent=true
 
#做种时间，两个小时，因为做种的任务也算在活动任务中，因此太长时间做种会阻碍新的下载任务
seed-time=120

# BT监听端口, 当端口被屏蔽时使用, 默认:6881-6999
#listen-port=51413

# 单个种子最大连接数, 默认:55
#bt-max-peers=55

# 打开DHT功能, PT需要禁用, 默认:true
#enable-dht=false

# 打开IPv6 DHT功能, PT需要禁用
#enable-dht6=false

# DHT网络监听端口, 默认:6881-6999
#dht-listen-port=6881-6999

#dht-file-path=/opt/var/aria2/dht.dat
#dht-file-path6=/opt/var/aria2/dht6.dat

# 本地节点查找, PT需要禁用, 默认:false
#bt-enable-lpd=false

# 种子交换, PT需要禁用, 默认:true
#enable-peer-exchange=false

# 每个种子限速, 对少种的PT很有用, 默认:50K
#bt-request-peer-speed-limit=50K

# 设置 peer id 前缀
peer-id-prefix=-TR2770-

# 当种子的分享率达到这个数时, 自动停止做种, 0为一直做种, 默认:1.0
seed-ratio=1

# 强制保存会话, 即使任务已经完成, 默认:false
# 较新的版本开启后会在任务完成后依然保留.aria2文件
force-save=true

# BT校验相关, 默认:true
#bt-hash-check-seed=true

# 继续之前的BT任务时, 无需再次校验, 默认:false
bt-seed-unverified=true

# 保存磁力链接元数据为种子文件(.torrent文件), 默认:false
bt-save-metadata=true

bt-max-open-files=16

##############
bt-tracker=udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.openbittorrent.com:80/announce,udp://9.rarbg.to:2710/announce,udp://9.rarbg.me:2710/announce,udp://tracker.opentrackr.org:1337/announce,udp://tracker.internetwarriors.net:1337/announce,udp://exodus.desync.com:6969/announce,udp://retracker.lanta-net.ru:2710/announce,udp://tracker.tiny-vps.com:6969/announce,udp://open.demonii.si:1337/announce,udp://open.stealth.si:80/announce,udp://denis.stalker.upeer.me:6969/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.cyberia.is:6969/announce,udp://torrentclub.tech:6969/announce,udp://tracker.moeking.me:6969/announce,udp://explodie.org:6969/announce,udp://tracker3.itzmx.com:6961/announce,udp://tracker.filepit.to:6969/announce,udp://retracker.baikal-telecom.net:2710/announce
enable-dht=true
bt-enable-lpd=true
enable-peer-exchange=true

**Comment by hehh2001** [comment]
Above is my configuration file    
/var/lib/docker/overlay2

The project took up a lot of space. In a week, my root partition was full, so that the system could not start this morning. I deleted it before it was normal. Then I rebuilt the docker container and found this problem.

**Comment by hehh2001** [comment]
I delete - v/srv/media/app/filebrowser.db:/app/filebrowser.db

After this item, the container is normal.

**Comment by wahyd4** [comment]
I just had a look at the docker container disk usage which is all good, also you are the first person who complains about disk usage. 

So I reckon you run the following command and keep eyes on it to see how the disk usage grows.  Report anything you found weird.


```console
➜  junv docker system df -v | grep aria2-ui
wahyd4/aria2-ui                                                  latest              c1cdd22e1056        5 weeks ago         101.2MB             0B                  101.2MB             1
wahyd4/aria2-ui                                                  nextcloud           ceb627278a28        8 months ago        73MB                4.413MB             68.59MB             0
wahyd4/aria2-ui                                                  20190219_1          8077ea624803        9 months ago        77.08MB             4.434MB             72.65MB             0
wahyd4/aria2-ui                                                  h5ai                27af18d5e008        14 months ago       91.46MB             4.148MB             87.32MB             0
da302627559c        wahyd4/aria2-ui:latest                   "./start.sh"              1                   63.6MB              30 days ago          Up 30 days                   aria2-ui
```

**Comment by hehh2001** [comment]
docker system df -v | grep aria2-ui 
wahyd4/aria2-ui           latest              7c96f2ce18fa        2 weeks ago         101.2MB             0B                  101.2MB             1
7d71fe8c534d        wahyd4/aria2-ui:latest           "./start.sh"        0                   3.09GB              11 minutes ago      Up 8 minutes        ariang
I'm really sorry. I checked it carefully, but I still can't find the reason for the problem.

**Comment by wahyd4** [comment]
Have a look the size of aria2 log file and any other log files. They all under `/var/logs/` folder

**Comment by hehh2001** [comment]
Thank you. I've been watching for a week. if have questeions to report to you.

**Comment by hehh2001** [comment]
https://blog.csdn.net/mofiu/article/details/79021550    　
https://blog.csdn.net/weixin_32820767/article/details/81196250
I found the reason here. It's my own problem. I'm sorry to disturb you!!
