### ISSUE TITLE
airaNg版本到1.1.4了

### ISSUE THREAD

**Issue by muziling** [wahyd4/aria2-ariang-docker#64]
docker更新很及时， 但内置的airaNg版本还停留在1.1.1

**Comment by Andyk1n** [comment]
你好在使用时候遇到了报错，采用的yaaw和airang的配合进行下载。然后报错如图
![image](https://user-images.githubusercontent.com/32835738/74587962-8b5e7900-5033-11ea-9fad-c837e11582e1.png)
![image](https://user-images.githubusercontent.com/32835738/74587971-987b6800-5033-11ea-8c30-cb555cb685ed.png)
看得懂错误描述：HTTP 返回头无效或无法识别.
但是无法理解意思，其他的airang的配置并没有提及报错解决，同时我Google以后也无法得到比较好的解决办法，请求帮助。
