### ISSUE TITLE
fileBrowser文件管理器管理员密码忘了有啥办法恢复呢

### ISSUE THREAD

**Issue by pcshao** [wahyd4/aria2-ariang-docker#74]
## Please try to use English to describe your question or issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by wahyd4** [comment]
The issue has been closed due to didn't follow the template instruction

**Comment by pcshao** [comment]
没看到格式，请问能解答问题吗

发自我的iPad

**Comment by wahyd4** [comment]
I am happy to answer this if you can open another issue and follow the template.
