### ISSUE TITLE
使用docker-compose解决“以非其他80 端口或以启用了HTTPS443端口运行程序时，会出现Aria2状态未连接的错误”

### ISSUE THREAD

**Issue by sanjusss** [wahyd4/aria2-ariang-docker#76]
我找到一种方法，解决“以非其他80 端口或以启用了HTTPS443端口运行程序时，会出现Aria2状态未连接的错误”。
在docker-compose的aria2服务末尾，直接增加command字段：
```yml
    command: 
      - bash
      - -c
      - |
          sed -i 's/80/443/g' /usr/local/www/aria2/js/aria-ng*.js
          /app/start.sh
```
其中443就是新端口号。这样就可以在不修改镜像的情况下，自动让ariang使用443端口了。
@wahyd4 建议添加一个环境变量，可以在启动时修改这个端口号。

**Comment by wahyd4** [comment]
Hi @sanjusss , thanks for your insight.

Do you want to make a pull request to introduce your thoughts?

**Comment by sanjusss** [comment]
我直接clone代码，运行以下命令：
```shell
docker build . -t test
docker run --rm -p 80:80 test
```
提示：
![image](https://user-images.githubusercontent.com/8220722/71360725-b3010a00-25cb-11ea-886e-26a26c3f020c.png)
貌似代码不能直接调试。请问该如何运行？
> Hi @sanjusss , thanks for your insight.
> 
> Do you want to make a pull request to introduce your thoughts?
