### ISSUE TITLE
Custom Domain and https error

### ISSUE THREAD

**Issue by gary19930520** [wahyd4/aria2-ariang-docker#80]
你好,

嘗試使用以下 docker 指令發現會在一開始時出錯（環境：Synology DSM6 Intel CPU Docker）

```
docker run -d --name aria2-ui-01 \
  -p 6880:80 \
  -p 6881:443 \
  -p 6800:6800 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e ENABLE_AUTH=true \
  -e RPC_SECRET=PASSWORD \
  -e DOMAIN=https://aria.domain.com \
  -e ARIA2_SSL=false \
  -e ARIA2_USER=admin \
  -e ARIA2_PWD=PASSWORD \
  -e ARIA2_EXTERNAL_PORT=443 \
  -v /volumeUSB1/usbshare/Aria2_Download:/data \
  -v /volume1/docker/aria2/cert:/app/conf/key \
  -v /volume1/docker/aria2/conf:/app/conf \
  wahyd4/aria2-ui
```

在 /volume1/docker/aria2/cert 中我有放至我自己 domain「aria.domain.com」的 wildcard 憑證並改名為 aria2.cert 及 aria2.key

crash 報錯圖為：
![Screen Shot 2020-01-25 at 5 07 03 PM](https://user-images.githubusercontent.com/7288694/73118872-40ea5f00-3f95-11ea-8455-001eb828d690.png)

想請問我是哪個步驟出錯了呢？謝謝

**Comment by wahyd4** [comment]
Looks like it was because of the cert itself. Please check a few items:

1. Make sure the `/key` folder has both `key` and `cert` files, 
2. Make sure the key and cert files are verified before you use it.

**Comment by wahyd4** [comment]
@gary19930520  Do you just want to enable `HTTPS` in browser? If so, the only need to change to`DOMAIN=https://your.domain`, don't need to have `/app/conf/key` set.
