### ISSUE TITLE
请问容器内forego进程的作用是什么呢？

### ISSUE THREAD

**Issue by JianleiZhang** [wahyd4/aria2-ariang-docker#82]
## Please try to use English to describe your question or issue.

**Describe the bug**
[https://github.com/wahyd4/aria2-ariang-docker/blob/4c16558d9ad3602b861a4ae4c6fde841f96ede15/Dockerfile#L27](get forego)

**Comment by JianleiZhang** [comment]
如果不复杂的话，可否用shell脚本代替。不可替代的话，能否开放一下源码？

**Comment by wahyd4** [comment]
It's the process manager to allow you to run multiple processes in the foreground at the same time. Please check more information here https://github.com/ddollar/forego

**Comment by wahyd4** [comment]
And currently, I have no plan to replace it because it works pretty good.
