### ISSUE TITLE
文件管理和说明文档不一致

### ISSUE THREAD

**Issue by sunzhaoyang** [wahyd4/aria2-ariang-docker#83]
## Please try to use English to describe your question or issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/2182116/76272061-438ae480-62b5-11ea-88c4-21f113efe6fa.png)

filemanager 默认127.0.0.1:8080 启动，没找到改成0.0.0.0:8080 的配置

**Comment by wahyd4** [comment]
This is docker! It's not the same as running a program directly on your host. So it doesn't matter how the logs showed up inside the container.   

The port you mapped to outside matters. 

```bash
  docker run -d --name aria2-ui -p 1234:80 wahyd4/aria2-ui
```

So in this example the `1234` is the port exposed on your host, you can use it to access this application. not `80` or `8080`.

**Comment by sunzhaoyang** [comment]
safari cache ,sorry~
