### ISSUE TITLE
Update to caddy 2

### ISSUE THREAD

**Issue by wahyd4** [wahyd4/aria2-ariang-docker#87]
# Description

Since Caddy is fully open source, it's better to upgrade caddy to version 2

**Comment by wahyd4** [comment]
This will be put on hold for a while, giving the Caddy is not stable and mature at all after trying for a while.😕

**Comment by acc557** [comment]
Looking forward to that!

Also, I found a nice dockerfile to build caddy 2 with webdav support. That would be useful for many GUI clients.  

```
FROM caddy:builder AS builder

RUN caddy-builder \
  github.com/mholt/caddy-webdav

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by acc557** [comment]
BTW, Caddy2 is stable already. :)
