### ISSUE TITLE
在 文件管理里创建的文件共享链接地址无法打开

### ISSUE THREAD

**Issue by gexiaopeng** [wahyd4/aria2-ariang-docker#92]
在 文件管理(File Browser 2.1.0)里创建的文件共享链接地址无法打开(有报js错误)

[截图1(screenshot1)](http://60.191.53.35:8760/shopportal/images/screenshot.png)

[截图2(screenshot2)](http://60.191.53.35:8760/shopportal/images/screenshot2.png)

**Comment by wahyd4** [comment]
@gexiaopeng Thanks for your reporting. It's been fixed now. Will push a new image version in minutes.

**Comment by gexiaopeng** [comment]
how do?
