### ISSUE TITLE
RPC_SECRET 设置无效

### ISSUE THREAD

**Issue by gexiaopeng** [wahyd4/aria2-ariang-docker#94]
我在docker 中设置了 RPC_SECRET，但在连接配置的 Aria2 RPC 密钥 中为空或者随便填一个也可以连接。（最新版本有问题，以前的版本是正常的）

**Comment by wahyd4** [comment]
According to the document of `aria2`, you can't just specify `RPC_SECRET`,  you will also need to enable `Encrypt RPC traffic with SSL/TLS`.  

Which means you this docker image, you will also need to set `ARIA2_SSL` to `true` and specify volumes for your `cert` and `key`.

More info please check https://aria2.github.io/manual/en/html/aria2c.html?highlight=rpc%20secret#encrypt-rpc-traffic-with-ssl-tls
