### ISSUE TITLE
NFS运行失败

### ISSUE THREAD

**Issue by juqkai** [wahyd4/aria2-ariang-docker#97]
arm64的盒子中，通过NFS进行磁盘挂载。
将NFS内某个目录指定为下载目录，会导致chown失败。
原因: [chown on a mounted NFS partition gives “Operation not permitted”](https://serverfault.com/questions/212178/chown-on-a-mounted-nfs-partition-gives-operation-not-permitted)
是不是可以不使用chown呢？

**Comment by wahyd4** [comment]
Of course.

I am also using an NFS mounted folder as a local folder and didn't run chown, it works fine.

**Comment by wahyd4** [comment]
By the way, I am using the `root` user to run this docker image with mounting an NFS folder. So I didn't run `chown`.  You can check out http://cn.linux.vbird.org/linux_server/0330nfs.php section 13.2.3 to find out more background information about `NFS squash`.

**Comment by wahyd4** [comment]
One solution would be set the NFS option to be `no_root_squash`, then run `chown` on your server which is your NFS client.
