### ISSUE TITLE
下载时连接数经常为1

### ISSUE THREAD

**Issue by gexiaopeng** [wahyd4/aria2-ariang-docker#99]
现在下载时（通过115插件）连接数经常是1，我家里是300M电信光纤，下载速度只有5-6MB/s左右。

[截图](http://60.191.53.35:8760/shopportal/images/speed.png)

**Comment by wahyd4** [comment]
I guess it's because 115 is not using `bt`. 

Furthermore, it's not an issue of this repo, you can go to aria2 repo to raise this issue.
